
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A42594CE32DA3A5D811CBEA2DBE18E42'
    
_lr_action_items = {'NOT':([2,],[4,]),'$end':([1,3,10,14,15,16,],[-5,0,-4,-1,-3,-2,]),'IMPLIES':([1,5,10,14,15,16,],[-5,7,-4,-1,-3,-2,]),'LPAREN':([0,2,4,7,8,9,],[2,2,2,2,2,2,]),'PREDICATE':([0,2,4,7,8,9,],[1,1,1,1,1,1,]),'AND':([1,5,10,14,15,16,],[-5,8,-4,-1,-3,-2,]),'OR':([1,5,10,14,15,16,],[-5,9,-4,-1,-3,-2,]),'RPAREN':([1,6,10,11,12,13,14,15,16,],[-5,10,-4,14,15,16,-1,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FORMULA':([0,2,4,7,8,9,],[3,5,6,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FORMULA","S'",1,None,None,None),
  ('FORMULA -> LPAREN FORMULA IMPLIES FORMULA RPAREN','FORMULA',5,'p_formula_binary','py.py',32),
  ('FORMULA -> LPAREN FORMULA OR FORMULA RPAREN','FORMULA',5,'p_formula_binary','py.py',33),
  ('FORMULA -> LPAREN FORMULA AND FORMULA RPAREN','FORMULA',5,'p_formula_binary','py.py',34),
  ('FORMULA -> LPAREN NOT FORMULA RPAREN','FORMULA',4,'p_formula_not','py.py',38),
  ('FORMULA -> PREDICATE','FORMULA',1,'p_formula_symbol','py.py',42),
]
